include $(TOPDIR)/rules.mk

PKG_VERSION:=2.32-r112021

LUCI_TITLE:=LuCI Support for nikki modifwwwwbbbbbbbbbbbb
LUCI_DEPENDS:=+luci-base +nikki +jqfdddsssssssssssssss

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
