include $(TOPDIR)/rules.mk

PKG_VERSION:=1.32-r1120211

LUCI_TITLE:=LuCI Support for nikki modifwwww
LUCI_DEPENDS:=+luci-base +nikki +jqfdd

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
