name: Update Repository from Upstream

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/nikkinikki-org/OpenWrt-nikki.git
          git fetch upstream

      - name: Merge upstream/main into main
        run: |
          git checkout main
          git merge upstream/main || true

      - name: Set remote url with token
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Push changes
        run: |
          git push origin HEAD:main
