name: Sync from Upstream

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # setiap hari jam 10:00 WIB

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/rivandraa/OpenWRT-Nikki-TProxy.git
          git fetch upstream

      - name: Merge changes from upstream/main
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories || true

      - name: Set remote url with PAT
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT_WORKFLOW }}@github.com/${{ github.repository }}.git

      - name: Push changes to my repo
        run: |
          git push origin main
